name: reviewdog
on: [push]
jobs:
 golint-check:
  runs-on: ubuntu-latest
  steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go lint check
        uses: reviewdog/action-golangci-lint@v2
        with:
         golangci_lint_flags: "golangci-lint run --out-format=line-number ./main.go"
         tool_name: golint
         level: error
         reporter: github-pr-check