name: reviewdog
on: [push]
jobs:
 golint-check:
  runs-on: ubuntu-latest
  steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go lint check
        env:
         REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: reviewdog -conf=./../../.reviewdog.yml -f=golint -reporter=github-pr-review