name: reviewdog
on: [push]
jobs:
 golint-check:
  name: Run reviewdog
  env:
   REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: reviewdog -conf=./../../.reviewdog.yml -f=golint -reporter=github-pr-review