name: reviewdog
on: [push]
jobs:
 golint-check:
  runs-on: ubuntu-latest
  steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      
      - name: Setup review dog
        uses: reviewdog/action-setup@v2

      - name: Go lint check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-check -runners=golint