name: reviewdog
on: [push]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          # optionally use a specific version of Go rather than the latest one
          go_version: "1.17"

          # Can pass --config flag to change golangci-lint behavior and target
          # directory.
          # golangci_lint_flags: "--config=.github/.golangci.yml ./..."
          
          workdir: ../../

  # Use golint via golangci-lint binary with "warning" level.
  golint:
    name: runner / golint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golint
        uses: reviewdog/action-golangci-lint@v2
        with:
          tool_name: golint # Change reporter name.
          level: error # GitHub Status Check won't become failure with this level.

  # You can add more and more supported linters with different config.
  errcheck:
    name: runner / errcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: errcheck
        uses: reviewdog/action-golangci-lint@v2
        with:
          tool_name: errcheck
          level: info


  golangci-lint-github-pr-review:
    name: runner / golangci-lint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint w/ github-pr-review
        uses: reviewdog/action-golangci-lint@v2
        with:
          tool_name: "golangci-lint-github-pr-review"
          reporter: "github-pr-review"
          workdir: ../../