name: learn-github-actions
on: [push]
jobs:
  reviewdog-github-check:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: reviewdog (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: actions/checkout@v3

      - name: Install linters
        run: go get -u golang.org/x/lint/golint

      - name: Setup & Run reviewdog
        uses: reviewdog/action-setup@v1
        # env:
        #   REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golint ./... | reviewdog -f=golint -name=golint-github-check -reporter=github-pr-check -level=warning
